# Generated by Django 4.2.16 on 2026-09-13 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=200)),
                ('gemini_model', models.CharField(blank=True, default='gemini-3.8-flash', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=150)),
                ('topics', models.TextField(blank=True, default='')),
                ('num_questions', models.PositiveIntegerField(default=0)),
                ('brief', models.TextField(blank=True, default='')),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_response_excerpt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='api.test')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
